const UserDataModel = {
    "performanceReviewPage":{
        "incoming":{
            "pending":[],
            "inProgress":[],
            "completed":[]
        },
        "outgoing":{
            "pending":[],
            "inProgress":[],
            "completed":[]
        }
    },
    "assignedTrainingPage":{
        "incoming":{
            "pending":[],
            "inProgress":[],
            "completed":[]
        },
        "outgoing":{
            "pending":[],
            "inProgress":[],
            "completed":[]
        }
    },
    "PTORequestPage":{
        "incoming":{
            "pending":[],
            "inProgress":[],
            "completed":[]
        },
        "outgoing":{
            "pending":[],
            "inProgress":[],
            "completed":[]
        }
    }
}

module.exports = UserDataModel;